name: "Fetch SSH key from AWS Secrets Manager"
description: "Fetch an SSH private key from AWS Secrets Manager, write it to disk, set permissions and optionally add it to ssh-agent."

inputs:
  secret:
    description: "The AWS Secrets Manager secret ID where the SSH private key is stored."
    required: true
  key:
    description: "The key name in the secret JSON that contains the SSH private key. If the secret is stored as a plain string, use an empty string."
    required: false

outputs:
  key:
    description: "The SSH private key fetched from Secrets Manager."
    value: ${{ steps.fetch_ssh.outputs.key }}
  token:
    description: "The Snyk token fetched from Secrets Manager."
    value: ${{ steps.fetch_ssh.outputs.token }}

runs:
  using: "composite"
  steps:
    - name: Fetch ssh key from Secrets Manager
      id: fetch_ssh
      shell: bash
      run: |
        # If your secret was stored as plain string, use --query SecretString --output text
        # If stored as JSON like {"SNYK_TOKEN":"..."} then pipe through jq
        SECRET=$(aws secretsmanager get-secret-value \
          --secret-id ${{ inputs.secret }} \
          --query SecretString \
          --output text)
        # echo "secret string (raw): $SECRET_JSON" >&2   # for debug (do not print token in real runs)
        # If the secret is JSON, extract the key:
        if echo "$SECRET" | jq -e ."${{ inputs.key }}" >/dev/null 2>&1; then
          SECRET_KEY=$(echo "$SECRET" | jq -r .${{ inputs.key }})
          echo "::add-mask::$SECRET_KEY"
          echo "token=$SECRET_KEY" >> "$GITHUB_OUTPUT"
        else
          # secret is raw token
          SECRET_KEY="$SECRET"
          # export as step output (masking not strictly necessary but helpful)
          SECRET_KEY_ESCAPED="${SECRET//$'\n'/'%0A'}"
          echo "::add-mask::$SECRET_KEY_ESCAPED"
          {
            echo "key<<EOF"
            echo "$SECRET_KEY"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
        fi